name: cryptsy
version: 0.0.1
author: Matt Smith
description: A library useful for applications or for sharing on pub.dartlang.org.
homepage: https://github.com/imthedoctor/cryptsy-dart
dependencies:
  cipher: any
  http: any
  crypto: any
dev_dependencies:
  unittest: any
