name: cryptsy
version: 0.0.1
author: Matt Smith
description: A library for interacting with the Cryptsy v2 API
homepage: https://github.com/imthedoctor/cryptsy-dart
dependencies:
  http: any
  crypto: any
dev_dependencies:
  unittest: any
